neon: fix build error on gcc-7
Build failed on ubuntu-18.04 with gcc-7.5, gcc doesn't support
vld1q_u8_x2() until version 8.

gcc  -g -O3 -Wall -march=native  -c -o range2-neon.o range2-neon.c
range2-neon.c: In function ‘utf8_range2’:
range2-neon.c:61:45: warning: implicit declaration of function ‘vld1q_u8_x2’; did you mean ‘vld1q_u32’? [-Wimplicit-function-declaration]
             const uint8x16x2_t input_pair = vld1q_u8_x2(data);
                                             ^~~~~~~~~~~
                                             vld1q_u32
range2-neon.c:61:45: error: invalid initializer